[workspace]
members = [
    "programs/dumplock_program"
]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
onchain_dumplock = "GoB3WxFTNYh8kqicpC1eYjnJCx9qpcy2TuGsVqB38pmz"

[provider]
cluster = "mainnet"

[scripts]
test = "mocha tests/dumplock_program.js"
